### ISSUE TITLE
Provide a clean error page when an error occurred

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/launchpad-missioncontrol#126]
Ideally, with an explanation of the cause of the problem (in particular, when the OpenShift project already exists)

**Comment by ALRubinger** [comment]
True, actually I'm thinking we don't issue redirects directly, but return a JSON response with the "Boom" and then the client can show the user.  In this was we can also wrap all errors in a JSON response and the client can show that if it's not an HTTP 200.

**Comment by ALRubinger** [comment]
Outdated; new event mechanism to show failures
