### ISSUE TITLE
CatapultResourceIT and CatapultConsoleIT should check the OS project was created correctly

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-missioncontrol#130]
After landing on the Overview page, use a test deployment to call into the `OpenShiftService` directly to inquire about the project that was set up and ensure that it's in the expected form (otherwise all we really do is test that a project was created).

**Comment by gastaldi** [comment]
This is already accomplished in https://github.com/openshiftio/launchpad-missioncontrol/issues/227. Closing
