### ISSUE TITLE
Remove Reliance on Catalog in Console

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-missioncontrol#165]
Delivery mechanism for reading the Catalog and firing the Catapult is now via the Obsidian Forge addon and Frontend.

Alter the console to instead accept text inputs, or upload a ZIP file to mock output from the Generator.

**Comment by gastaldi** [comment]
What console? The UI?

**Comment by ALRubinger** [comment]
@gastaldi Yes; right now the Catapult index.html reads from the Catalog (which we changed); and we should alter this to instead accept simple inputs for testing

**Comment by ALRubinger** [comment]
And, you know, the integration test is now broken :)

**Comment by ALRubinger** [comment]
79d0a19ba9293f2056dd9e0b5fcdd79cba53bf8d
