### ISSUE TITLE
Pipeline message is not displayed anymore top of the overview openshift web screen

### ISSUE THREAD

**Issue by cmoulliard** [openshiftio/launchpad-missioncontrol#206]
Pipeline message is not displayed anymore top of the overview openshift web screen

Maybe this issue is related to the fact that the Buildconfig object created doesn't include the OpenShift annotation used to display the pipeline progress bar

See : https://github.com/openshift/origin-web-console/issues/972

**Comment by ALRubinger** [comment]
Closing, tracking as duplicate #212 . thanks @cmoulliard - ported relevant info you've provided here to the new issue
