### ISSUE TITLE
Enable pipeline visualization on the Overview page

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-missioncontrol#212]
For some reason this doesn't appear to be working:

 https://github.com/openshiftio/launchpad-missioncontrol/blob/master/services/openshift-service-impl/src/main/resources/openshift-project-template.json#L23

We'd like the pipeline progress to be visible from the overview page.  Investigate and fix.

**Comment by ALRubinger** [comment]
Perhaps @spadgett might help us, reference:  

https://github.com/openshift/origin-web-console/pull/1335

**Comment by quintesse** [comment]
@edewit fixed this in b896065
