### ISSUE TITLE
Enable tracking of "launch" operation

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-missioncontrol#235]
openshiftio/appdev-planning#13

**Comment by ALRubinger** [comment]
Sending to @quintesse ; feel free to use my 4a1d507 as a base

**Comment by quintesse** [comment]
Already using parts of it. Btw, how is the token used? Can I see its results somewhere or would that mean using your user?

**Comment by ALRubinger** [comment]
@quintesse Emailed you access

**Comment by ALRubinger** [comment]
Reverted in 640f4d8; broken build due to compilation error: https://ci.centos.org/view/Devtools/job/devtools-launchpad-missioncontrol-generator-build-master/37/console

N/P, let's just fix up and try again :)

**Comment by ALRubinger** [comment]
@gastaldi @quintesse ^

**Comment by quintesse** [comment]
And stay closed!
