### ISSUE TITLE
Explore usage of fabric8-arquillian for integration testing

### ISSUE THREAD

**Issue by sabre1041** [openshiftio/launchpad-missioncontrol#24]
Utilize the [fabric8-arquillian](http://fabric8.io/gitbook/arquillian.html) to facilitate integration testing
- Configure project to support Arquillian
- Migrate existing IT tests to Arquillian framework

**Comment by ALRubinger** [comment]
Ongoing discussion w/ @sabre1041 to determine the project needs vs. what fabric8-arquillian provides.  TBD :)

**Comment by ALRubinger** [comment]
Also sent message to continuous-dev detailing the steps we might take.  fabric8-arquillian isn't a requirement but a possible implementation choice IMO.

**Comment by sabre1041** [comment]
@ALRubinger I updated the title to clarify this issue as a discovery task

**Comment by ALRubinger** [comment]
Moving towards arquillian-cube when we have testing strategy available; out of date
