### ISSUE TITLE
Launchpad Content sourced from the docs not rendering correctly

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/launchpad-missioncontrol#241]
There are several replaceables (e.g. {OpenShiftLocal}) that should be getting replaced showing up on the launchpad. There is also an auto-title link thats not getting populated, but i'll fix that on the docs side.

**Comment by ALRubinger** [comment]
Removed references to these (and they're in launchpad-frontend and appdev-documentation) :)
