### ISSUE TITLE
Generate custom README file when booster gets created

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/launchpad-missioncontrol#259]
Have mission control create a custom README file for each booster when its cloned to a user's repo. This can be based on a template from the docs repo.

The launchpad should:
1. copy readme template from docs repo
1. update it with project-specific info (e.g. repo url)
1. commit and push it to the repo.

Project-specific info needed for insertion into the template:

* git repo url for cloning, e.g. `git@github.com:rhoads-zach/demo6271.git`
* project name, e.g. `demo6271`
* start command for local project, e.g. `mvn spring-boot:run`
* location of index.html, e.g. `src/main/resources/static/index.html`
* oso deployment command from the CLI: e.g.  `mvn clean fabric8:deploy -Popenshift -DskipTests`
* name of and link to specific runtime guide: e.g. `[Spring Boot Tomcat Runtime Guide](http://appdev.openshift.io/docs/mission-http-api-spring-boot-tomcat.html)`

More caveats:
* we need to handle SSO with a separate template
* we need figure out configmap, healthcheck, circuit breaker, and crud since running "locally"

**Comment by rhoads-zach** [comment]
@gastaldi can you pull a specific template file per mission?

**Comment by gastaldi** [comment]
@rhoads-zach Yes, I have the mission and the runtime parameters available in mission-control.

**Comment by rhoads-zach** [comment]
thank you @gastaldi @ALRubinger are there any details or ideas you want to add?

**Comment by rhoads-zach** [comment]
@gastaldi how do you want the replaceable to look in the readme file?

you ok with something like:
{gitHubProjectCloneURL}

**Comment by gastaldi** [comment]
It would be nice to use the following syntax for variables: `${gitHubProjectCloneURL}`

**Comment by rhoads-zach** [comment]
@gastaldi you got it, i'll drop in a branch with the templates as soon as i have it

**Comment by gastaldi** [comment]
Here are some variables that can be used:
 
`${projectile.mission}` = Mission name
`${projectile.runtime}` = Runtime name 
`${targetRepository.fullName}` = Target Git Hub repository name

**Comment by gastaldi** [comment]
Continuing work in https://github.com/openshiftio/launchpad-addon/issues/33

**Comment by gastaldi** [comment]
Reopening as some information is available only in Mission control
