### ISSUE TITLE
Enhance OpenShiftApiUrl to pick up API URL of OpenShift if we are running in OpenShift

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-missioncontrol#45]
Priority should be (lower numbers means higher priority):

1) System Property {@link org.kontinuity.catapult.service.openshift.api.OpenShiftEnvVarSysPropNames#OPENSHIFT_URL}
2) Environment Variable {@link org.kontinuity.catapult.service.openshift.api.OpenShiftEnvVarSysPropNames#OPENSHIFT_URL}
3) Current instance of OpenShift we are running in
4) {@link OpenShiftApiUrl#DEFAULT_OPENSHIFT_URL}

**Comment by rimolive** [comment]
Isn't this class implemented? Is there something missing?

**Comment by ALRubinger** [comment]
Yep, we're missing step 3).  Right now we only have the env var, sysprop, and default approach.

**Comment by ALRubinger** [comment]
@quintesse Is there some kind of sysprop provided by K8s or OpenShift which tells us the equivalent of `minishift console --url` if we're running in an OpenShift instance?

**Comment by ALRubinger** [comment]
If we can implement this, we can make it so the user doesn't have to supply the env var when processing the template

**Comment by quintesse** [comment]
I've been busy looking for this but the only thing I've found so far is something that's not externally accessible. I think we'll have to ask someone from the OpenShift team.

**Comment by quintesse** [comment]
I've at least asked for help on the OpenShift mailing list. But if someone knows a more direct route to any OpenShift experts, please let me know.

**Comment by quintesse** [comment]
I've not gotten a response yet from the OpenShift Google Group so I resent the same question to RH's OpenShift user mailing list. Let's see if that gets us some result.

**Comment by quintesse** [comment]
Seems we might have to forget about this one. THey tell me it's not doable right now:

https://lists.openshift.redhat.com/openshift-archives/users/2017-April/msg00008.html

**Comment by ALRubinger** [comment]
Closing as we don't have the supporting infra for this now.  If we can't solve this in the template than maybe eventually we solve at a layer above.
