### ISSUE TITLE
Refactor GitHubService > GitService

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-missioncontrol#87]
Really the API has nothing to do with GitHub, and we will be needing to support other Git providers in the future.

So let's:

1) Rename module `github-service-api` > `git-service-api`
2) Rename package `org.kontinuity.catapult.service.github.api` > `org.kontinuity.catapult.service.git.api`
3) Rename module `github-service-impl` > `git-service-impl-github`
4) Rename package structure `org.kontinuity.catapult.service.github.impl.kohsuke` > `org.kontinuity.catapult.service.git.impl.github(.kohsuke)`
5) Rename `artifactId`s in POMs to match the changes above
6) Create another module to house the SPI; this can't be tied to any impl module any longer as the SPI will be eventually shared among N impls

In this way we open ourselves up to more impls with other git providers.

Whoever does this: coordinate with @alrubinger on timing because we don't wanna make merging inflight PRs more difficult.

**Comment by gastaldi** [comment]
IMHO the API has to do with Github (Create Repositories, Forking) and except for pushing, those are still actions that only work on Github.

**Comment by ALRubinger** [comment]
Closing as this is a non-requirement until we need to integrate with other providers.
