### ISSUE TITLE
Embrace failure

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/launchpad-missioncontrol#98]
This issue is an open question: how do we handle failures while processing the user's request, and more importantly, how do we recover ? I think that we should for example skip the git repository fork operation is it was done in a previous attempt, etc. 
If the whole 'fling' operation fails (network issue, timeout, etc.), the user will probably try again and in that case, the Catapult application should be able to carry on from where it failed.

**Comment by ALRubinger** [comment]
I think this should likely be handled by catching any `RuntimeException` in the HTTP endpoint where we expose `fling`, and return a 500-level error to the user

**Comment by ALRubinger** [comment]
Outdated; new event mechanism should show failures.
